### ISSUE TITLE
day4 启动报错 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by leffss** [geektutu/7days-golang#5]
day4 启动报错：
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x66dfda]

goroutine 1 [running]:
gee/gee.getNestPrefix(0x0, 0x0, 0x0, 0x8, 0x6a3440)
        E:/go_project/src/gee/gee/gee.go:88 +0x3a
gee/gee.(*RouterGroup).addRoute(0xc0000562c0, 0x711e2d, 0x3, 0x7123d1, 0x6, 0x72
ab98)
        E:/go_project/src/gee/gee/gee.go:63 +0x4b
gee/gee.(*RouterGroup).GET(...)
        E:/go_project/src/gee/gee/gee.go:69
main.main()
        E:/go_project/src/gee/main.go:45 +0x185
```

在 gee.go 添加以下方法后就可以了：
```go
func (engine *Engine) addRoute(method string, pattern string, handler HandlerFunc) {
	engine.router.addRoute(method, pattern, handler)
}

// GET defines the method to add GET request
func (engine *Engine) GET(pattern string, handler HandlerFunc) {
	engine.addRoute("GET", pattern, handler)
}

// POST defines the method to add POST request
func (engine *Engine) POST(pattern string, handler HandlerFunc) {
	engine.addRoute("POST", pattern, handler)
}
```
但是在 day5 没有这三个方法也正常运行，请问为什么呢？
还有非常喜欢大佬的教程，就是 day3 的 trie 树目前也不是特别懂

**Comment by geektutu** [comment]
day4 之前有个同学提了个PR，没仔细看就合入了，今天已经修复了，感谢你的关注呢~

**Comment by xutaoa** [comment]
@leffss 能贴出代码么 哪里出问题了

**Comment by geektutu** [comment]
@xutaoa  getNestPrefix 可能会出现空指针异常，然后 Group 嵌套用这种方式也是OK的，每个子Group初始化时添加上父 Group 的 prefix，层层往下，也是嵌套的。

```go
newGroup := &RouterGroup{
	prefix: group.prefix + prefix,
        ...
}
```

测试用例也更新了

```go
func TestNestedGroup(t *testing.T) {
	r := New()
	v1 := r.Group("/v1")
	v2 := v1.Group("/v2")
	v3 := v2.Group("/v3")
	if v2.prefix != "/v1/v2" {
		t.Fatal("v2 prefix should be /v1/v2")
	}
	if v3.prefix != "/v1/v2/v3" {
		t.Fatal("v2 prefix should be /v1/v2")
	}
}
```

**Comment by xutaoa** [comment]
@geektutu 
```
// 循环处理嵌套问题
func getNestPrefix(group *RouterGroup, p string) string {
	if group == nil {
		return p
	}
	p = strings.Join([]string{group.prefix, p}, "")
	if group.parent == nil {
		return p
	}
	return getNestPrefix(group.parent, p)
}
```
这样就可以了，本地代码是改了，忘记提交了😳 感谢回复
